import { Product } from "./schemas/product"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Nike Air Force 1 Mid",
    type: "Men's Shoes",
    price: 180,
    colors: 5,
    image: "/Nike Air Force 1 Mid '07.png",
    badge: { text: "Deal Bailer", color: "red" },
  },
  {
    id: "2",
    name: "Nike Court Vision Low Next Nature",
    type: "Men's Shoes",
    price: 180,
    colors: 4,
    image: "/Nike Court Vision Low Next Nature.png",
    badge: { text: "Exotic 20% off", color: "green" },
  },
  {
    id: "3",
    name: "Nike Air Force 1 Recrafted",
    type: "Men's Shoes",
    price: 180,
    colors: 1,
    image: "/Nike Air Force 1 PLTAFORM.png",
    badge: { text: "Sustainable Materials", color: "green" },
  },
  {
    id: "4",
    name: "Nike Dunk Low Retro",
    type: "Men's Shoes",
    price: 100,
    colors: 5,
    image: "/Nike Dunk Low Retro.png",
    badge: { text: "Deal Bailer", color: "red" },
  },
  {
    id: "5",
    name: "Nike Air Max SYSTM",
    type: "Men's Shoes",
    price: 100,
    colors: 4,
    image: "/Nike Air Max SYSTM.png",
    badge: { text: "Exotic 20% off", color: "green" },
  },
  {
    id: "6",
    name: "Nike Air Force 1 Recrafted",
    type: "Men's Shoes",
    price: 180,
    colors: 1,
    image: "/Nike Air Force 1 PLTAFORM (2).png",
    badge: { text: "Deal Bailer", color: "red" },
  },
  {
    id: "7",
    name: "Nike Dunk Low Retro SE",
    type: "Men's Shoes",
    price: 100,
    colors: 4,
    image: "/Nike Dunk Low Retro SE.png",
    badge: { text: "Exotic 20% off", color: "green" },
  },
  {
    id: "8",
    name: "Nike Air Max 90 SE",
    type: "Men's Shoes",
    price: 180,
    colors: 3,
    image: "/Nike Air Max 90 SE.png",
    badge: { text: "Deal Bailer", color: "red" },
  },
  {
    id: "9",
    name: "Nike Legend Essential 2",
    type: "Men's Training Shoes",
    price: 180,
    colors: 1,
    image: "/Nike Legend Essential 3 Next Nature.png",
    badge: { text: "Exotic 20% off", color: "green" },
  },
  {
    id: "10",
    name: "Nike SB Zoom Janoski OG",
    type: "Men's Shoes",
    price: 180,
    colors: 2,
    image: "/Nike SB Zoom Janoski OG+.png",
    badge: { text: "Deal Bailer", color: "red" },
  },
  {
    id: "11",
    name: "Jordan Series ES",
    type: "Men's Shoes",
    price: 180,
    colors: 2,
    image: "/Jordan Series ES.png",
    badge: { text: "Sustainable Materials", color: "green" },
  },
  {
    id: "12",
    name: "Nike Blazer Low 77 Jumbo",
    type: "Women's Shoes",
    price: 180,
    colors: 1,
    image: "/Nike Blazer Low '77 Jumbo.png",
    badge: { text: "Exotic 20% off", color: "green" },
  },
]
