import { Product } from "./schemas/product"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Nike Air Force 1 Mid",
    category: "Shoes",
    gender: "Men",
    sport: "Lifestyle",
    price: 180,
    colors: ["Black", "White", "Red", "Blue", "Grey"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Air Force 1 Mid '07.png",
    badge: "Deal Bailer",
  },
  {
    id: "2",
    name: "Nike Court Vision Low Next Nature",
    category: "Shoes",
    gender: "Men",
    sport: "Lifestyle",
    price: 180,
    colors: ["White", "Black", "Green", "Navy"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Court Vision Low Next Nature.png",
    badge: "Exotic 20% off",
  },
  {
    id: "3",
    name: "Nike Air Force 1 Recrafted",
    category: "Shoes",
    gender: "Men",
    sport: "Lifestyle",
    price: 180,
    colors: ["White"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Air Force 1 PLTAFORM.png",
    badge: "Sustainable Materials",
  },
  {
    id: "4",
    name: "Nike Dunk Low Retro",
    category: "Shoes",
    gender: "Men",
    sport: "Basketball",
    price: 100,
    colors: ["Black", "White", "Red", "Blue", "Yellow"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Dunk Low Retro.png",
    badge: "Deal Bailer",
  },
  {
    id: "5",
    name: "Nike Air Max SYSTM",
    category: "Shoes",
    gender: "Men",
    sport: "Running",
    price: 100,
    colors: ["White", "Black", "Grey", "Red"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Air Max SYSTM.png",
    badge: "Exotic 20% off",
  },
  {
    id: "6",
    name: "Nike Air Force 1 Recrafted",
    category: "Shoes",
    gender: "Men",
    sport: "Lifestyle",
    price: 180,
    colors: ["White"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Air Force 1 PLTAFORM (2).png",
    badge: "Deal Bailer",
  },
  {
    id: "7",
    name: "Nike Dunk Low Retro SE",
    category: "Shoes",
    gender: "Men",
    sport: "Basketball",
    price: 100,
    colors: ["Black", "White", "Orange", "Green"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Dunk Low Retro SE.png",
    badge: "Exotic 20% off",
  },
  {
    id: "8",
    name: "Nike Air Max 90 SE",
    category: "Shoes",
    gender: "Men",
    sport: "Running",
    price: 180,
    colors: ["White", "Black", "Red"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Air Max 90 SE.png",
    badge: "Deal Bailer",
  },
  {
    id: "9",
    name: "Nike Legend Essential 2",
    category: "Training Shoes",
    gender: "Men",
    sport: "Training",
    price: 180,
    colors: ["Black"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike Legend Essential 3 Next Nature.png",
    badge: "Exotic 20% off",
  },
  {
    id: "10",
    name: "Nike SB Zoom Janoski OG",
    category: "Shoes",
    gender: "Men",
    sport: "Skateboarding",
    price: 180,
    colors: ["Black", "White"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Nike SB Zoom Janoski OG+.png",
    badge: "Deal Bailer",
  },
  {
    id: "11",
    name: "Jordan Series ES",
    category: "Shoes",
    gender: "Men",
    sport: "Basketball",
    price: 180,
    colors: ["Black", "Red"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    imageUrl: "/Jordan Series ES.png",
    badge: "Sustainable Materials",
  },
  {
    id: "12",
    name: "Nike Blazer Low 77 Jumbo",
    category: "Shoes",
    gender: "Women",
    sport: "Lifestyle",
    price: 180,
    colors: ["White"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    imageUrl: "/Nike Blazer Low '77 Jumbo.png",
    badge: "Exotic 20% off",
  },
]
